apiVersion: v1
kind: Service
metadata:
  name: slo-demo-app
  namespace: default
  labels:
    app: slo-demo-app
spec:
  selector:
    app: slo-demo-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000