apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: slo-demo-app
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: slo-demo-app
  endpoints:
    - port: "8000"
      path: /metrics
      interval: 15s